name: Security & Code Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_quality:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: http://localhost:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------
      # Code Quality & Security with CodeQL
      # ------------------------
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java, javascript, python, go
          # You can add custom queries if needed
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # ------------------------
      # Static Analysis (SAST) with SonarQube
      # ------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=crop-price-dashboard
            -Dsonar.organization=your-org
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.login=${{ env.SONAR_TOKEN }}
        continue-on-error: false

      # ------------------------
      # Dynamic Analysis (DAST) with OWASP ZAP
      # ------------------------
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:8080' # Replace with your running app URL
          format: 'html'
          output: 'zap_report.html'
          failOnError: true
