name: Security Checks Only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    env:
      SONAR_HOST_URL: http://localhost:9000
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ------------------------
      # Static Analysis (SAST) with SonarQube
      # ------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=crop-price-dashboard
            -Dsonar.organization=your-org
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
            -Dsonar.login=${{ env.SONAR_TOKEN }}
        continue-on-error: false   # Fail workflow if serious issues found

      # ------------------------
      # Dynamic Analysis (DAST) with OWASP ZAP
      # ------------------------
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:8080' # Replace with your running app URL
          format: 'html'
          output: 'zap_report.html'
          failOnError: true   # Fail workflow if high risk vulnerabilities are detected
